apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: hello-arc
  namespace: hello-arc
  annotations:
    clusterconfig.azure.com/use-managed-source: "true"
spec:
  interval: 1m
  releaseName: hello-arc
  chart:
    spec:
      chart: ./hello-arc/charts/hello-arc
  values:
    image:
      repository: azurearcjumpstart.azurecr.io/hello-arc-gitops
      tag: latest
    replicaCount: 1
    env:
      name: MESSAGE
      value: Skolavslutning 13 Juni!!
